services:
  - type: web
    name: huntsville-district3-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
